name: strive
version: 5.0.9

category: API
description: Strive is a client for the Strava V3 API.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/strive
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: A client for the Strava V3 API.

dependencies:
  aeson: '>= 0.11.2 && < 0.12 || >= 1.0.2 && < 1.5'
  base: '>= 4.9.0 && < 4.15'
  bytestring: '>= 0.10.8 && < 0.11'
  data-default: '>= 0.7.1 && < 0.8'
  gpolyline: '>= 0.1.0 && < 0.2'
  http-client: '>= 0.4.31 && < 0.7'
  http-client-tls: '>= 0.2.4 && < 0.4'
  http-types: '>= 0.9.1 && < 0.13'
  template-haskell: '>= 2.11.0 && < 2.17'
  text: '>= 1.2.2 && < 1.3'
  time: '>= 1.6.0 && < 1.10'
  transformers: '>= 0.5.2 && < 0.6'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: impl(ghc >= 8.8.1)
    ghc-options: -Wno-missing-deriving-strategies

library:
  source-dirs: library

tests:
  test:
    dependencies:
      markdown-unlit: '>= 0.4.0 && < 0.6'
      strive: -any
    ghc-options:
      - -pgmL markdown-unlit
      - -rtsopts
      - -threaded
      - -Wno-missing-import-lists
    main: README.lhs
